apiVersion: v1
kind: Service
metadata:
  name: nexus-relay
  namespace: nexus
  labels:
    app: nexus-relay
spec:
  type: LoadBalancer
  selector:
    app: nexus-relay
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: metrics
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
